### ISSUE TITLE
IPython dependency issue

### ISSUE THREAD

**Issue by sasha42** [fixme-lausanne/screen-calendar#1]
On first run it specifies that `IPython` is not installed, requires manual installation:

``` bash
pi@raspberry ~/screen-calendar $ python screen.py
Traceback (most recent call last):
  File "screen.py", line 27, in <module>
    from IPython import embed
ImportError: No module named IPython
```

**Comment by gcmalloc** [comment]
wait what ? you don't need IPython for everything, especially if you don't use it !

**Comment by rorist** [comment]
it was for debugging purpose, should have been commented, sorry.
