### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by sasha42** [fixme-lausanne/screen-calendar#3]
Screen-calendar runs into the following error upon running from 7e0b3fde4113d33912696ef87e325aa89a9507ce:

``` bash
$ python screen.py 
  File "screen.py", line 112
    except TypeError, f:
         ^
SyntaxError: invalid syntax
```

I have encountered this issue both on RPi (Debian) and Mac.

**Comment by diadzine** [comment]
Which version of Python?

I think it's because syntax with comma is deprecated in Python 2.7 and removed in Python 3: https://docs.python.org/3.0/whatsnew/3.0.html#changes-to-exceptions

Change with: 
except TypeError as f:

**Comment by sasha42** [comment]
`Python 2.7.6` on mac and `Python 2.7.3` on the Pi.

Should there be a notice to use Python 3 in this case?

**Comment by rorist** [comment]
This is not the problem here, there's a syntax error the line before. The scripts forces the use of python2 anyway.

**Comment by gcmalloc** [comment]
maybe add some testing to the project ?

**Comment by rorist** [comment]
If you want, but it's a 150 lines script... not a modular thousands of lines project.

**Comment by gcmalloc** [comment]
You mean adding a travis project with:

```
python -m py_compile screen.py
```

is only for thousand line projects ?
